# Generated by Django 5.0.6 on 2026-06-23 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='whatsapp_message_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
    ]
