# Generated by Django 5.0.6 on 2026-07-01 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0002_interaction_whatsapp_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='media_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
